db.url=jdbc:postgresql://ep-wandering-mud-amez474h-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
db.username=neondb_owner
db.password=npg_TflJbGEV95XQ
db.driver=org.postgresql.Driver